name: CI
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.1'
      - run: npm install
      - name: Build dev
        run: |
          npm run build
          Copy-Item ./dist C:\angular\backend-dev -Recurse -Force
      - name: Build prod
        run: |
          npm run build:prod
          Copy-Item ./dist C:\angular\backend-prod -Recurse -Force
