name: CI
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.1'
      - run: npm install -f
      - name: Build dev
        run: npm run build
      - name: Deploy dev    
        run: Copy-Item ./dist C:\Users\Administrator\Documents\Project\中科大體溫機\AngularDeploy\build-project\backend-dev -Recurse -Force
      - name: Build prod
        run: npm run build:prod
      - name: Deploy prod    
        run: Copy-Item ./dist C:\Users\Administrator\Documents\Project\中科大體溫機\AngularDeploy\build-project\backend-prod -Recurse -Force
